"""Streamlit demo: Skin Lesion Detection using Multiresolution Analysis.
UI only; all image processing lives in src/ (call src.pipeline.analyse)."""
import hashlib
import json
import warnings

import cv2
import joblib
import numpy as np
import pandas as pd
import streamlit as st

import config
from src import pipeline, preprocessing
from src.errors import InvalidImageError, NoLesionError

warnings.filterwarnings("ignore")
NAVY, TEAL, CORAL, GREY = "#1F3A5F", "#2A9D8F", "#E76F51", "#F4F6F8"
DISCLAIMER = ("**Educational demo only.** This tool is not a medical device and must not be "
              "used for diagnosis. Images are processed locally and never stored.")

st.set_page_config(page_title="Skin Lesion Detection · Multiresolution Analysis",
                   page_icon="🔬", layout="wide")
st.markdown(f"<style>{(config.ROOT / 'assets' / 'style.css').read_text()}</style>",
            unsafe_allow_html=True)


# ---------- helpers ----------
@st.cache_resource
def load_model():
    return joblib.load(config.MODEL_PATH)


@st.cache_data(show_spinner=False)
def samples():
    """Demo samples are generated by make_figures.py (they are PH2 images, not in the repo)."""
    f = config.SAMPLES_DIR / "samples.json"
    return json.loads(f.read_text()) if f.exists() else {}


@st.cache_data(show_spinner=False)
def run_analysis(image_bytes, filename, wavelet, level, hair):
    rgb = preprocessing.decode_image(image_bytes, filename)
    return pipeline.analyse(rgb, wavelet, level, hair, model=load_model())


def disp(a, mask=False):
    """Convert any array to an image Streamlit can show."""
    a = np.asarray(a)
    if mask or a.dtype == bool:
        return (a.astype(np.uint8) * 255)
    if a.dtype != np.uint8:
        a = a.astype(np.float32)
        a = (a - a.min()) / (a.max() - a.min() + 1e-8) * 255
    return a.astype(np.uint8)


def band_img(b):
    b = np.abs(np.asarray(b, np.float32))
    return (np.clip(b / (np.percentile(b, 99) + 1e-8), 0, 1) * 255).astype(np.uint8)


def show(col, img, caption):
    col.image(img, caption=caption, width="stretch", clamp=True)


def disclaimer():
    st.warning(DISCLAIMER, icon="⚠️")


def error_card(title, body):
    st.error(f"**{title}**  \n{body}")


# ---------- state ----------
ss = st.session_state
ss.setdefault("source", None)   # {"name", "bytes", "sample"}
ss.setdefault("outcome", None)  # {"result"|"error", ...}


def pick_sample(key):
    path = config.SAMPLES_DIR / f"{key}.png"
    ss.source = {"name": f"{key}.png", "bytes": path.read_bytes(), "sample": key}
    ss.outcome = None


def on_upload():
    f = ss.get("uploader")
    if f is not None:
        ss.source = {"name": f.name, "bytes": f.getvalue(), "sample": None}
        ss.outcome = None


# ---------- sidebar ----------
with st.sidebar:
    st.header("Input")
    st.file_uploader("Upload a dermoscopy image", type=None, key="uploader", on_change=on_upload)
    st.caption("Supported: JPG, PNG, BMP · min 128×128 px · max 10 MB")
    if samples():
        st.markdown("**Or try a sample** (training-set images)")
        for key, info in samples().items():
            st.button(info["clinical"], key=f"s_{key}", on_click=pick_sample, args=(key,),
                      width="stretch")
    st.header("Settings")
    wavelet = st.selectbox("Wavelet", config.WAVELETS,
                           index=config.WAVELETS.index(config.WAVELET))
    level = st.slider("Decomposition level", 1, 3, config.LEVEL)
    hair = st.checkbox("Hair removal", value=config.HAIR_REMOVAL)
    with st.container(key="action"):
        if ss.source is not None:
            st.markdown(f'<div class="picked">Selected <b>{ss.source["name"]}</b></div>',
                        unsafe_allow_html=True)
        else:
            st.markdown('<div class="picked none">No image selected yet</div>',
                        unsafe_allow_html=True)
        analyse_clicked = st.button("Analyse", type="primary", width="stretch",
                                    disabled=ss.source is None, key="analyse")

if analyse_clicked and ss.source is not None:
    with st.spinner("Running multiresolution analysis…"):
        try:
            res = run_analysis(ss.source["bytes"], ss.source["name"], wavelet, level, hair)
            ss.outcome = {"result": res, "sample": ss.source["sample"],
                          "key": hashlib.md5(ss.source["bytes"]).hexdigest()}
        except InvalidImageError as e:
            ss.outcome = {"error": ("Invalid file", str(e))}
        except NoLesionError:
            ss.outcome = {"error": ("No lesion found",
                                    "Try a clearer, well-lit dermoscopy image of a single lesion.")}

# ---------- main ----------
st.markdown("""<div class="hero">
  <h1>Skin Lesion Detection<br>using Multiresolution Analysis</h1>
  <p class="sub">See how wavelets and morphology find a lesion in a dermoscopy image, step by step,
  and how a classifier scores it for melanoma.</p>
  <div class="chips"><span class="chip">Haar · db4 · sym4 wavelets</span>
  <span class="chip t">Image pyramids</span><span class="chip">Morphology</span>
  <span class="chip c">SVM melanoma score</span><span class="chip t">PH2 dataset</span></div>
</div>""", unsafe_allow_html=True)
tab_pipe, tab_res, tab_about = st.tabs(["Pipeline", "Result", "About"])
out = ss.outcome

with tab_pipe:
    if out is None:
        st.info("Upload a dermoscopy image" + (" or pick a sample" if samples() else "") +
                " in the sidebar, then press **Analyse**.")
    elif "error" in out:
        error_card(*out["error"])
    else:
        res, im = out["result"], out["result"]["images"]
        st.subheader("1 · Preprocessing: hair removal (Unit 7, morphology)")
        c = st.columns(3)
        show(c[0], im["original"], "Original (256×256)")
        show(c[1], disp(im["hair_mask"], True), "Black-hat hair mask")
        show(c[2], im["hair_removed"], "Hair removed (Telea inpainting)")

        st.subheader("2 · Multiresolution analysis (Unit 6, DWT)")
        lv = st.selectbox("Show subbands of level", sorted(im["subbands"]),
                          index=len(im["subbands"]) - 1, key="band_level")
        sb = im["subbands"][lv]
        c = st.columns(4)
        show(c[0], disp(sb["LL"]), f"LL · level {lv} (approximation)")
        show(c[1], band_img(sb["H"]), f"LH · level {lv} (horizontal detail)")
        show(c[2], band_img(sb["V"]), f"HL · level {lv} (vertical detail)")
        show(c[3], band_img(sb["D"]), f"HH · level {lv} (diagonal detail)")
        with st.expander("Gaussian and Laplacian pyramids (Unit 6)"):
            g, lap = im["gaussian_pyramid"], im["laplacian_pyramid"]
            c = st.columns(len(g))
            for i, a in enumerate(g):
                show(c[i], disp(a), f"Gaussian level {i}")
            c = st.columns(len(lap))
            for i, a in enumerate(lap):
                show(c[i], disp(a) if i == len(lap) - 1 else band_img(a), f"Laplacian level {i}")

        st.subheader("3 · Segmentation (Unit 7, Otsu + morphology)")
        c = st.columns(3)
        show(c[0], disp(im["coarse_mask"], True), "Coarse mask (Otsu on LL)")
        show(c[1], disp(im["final_mask"], True), "Final mask (open, close, fill)")
        show(c[2], im["overlay"], "Lesion contour overlay")
        with st.expander("Timings"):
            m = res["meta"]
            st.write(f"Total {m['time_ms']} ms · " +
                     " · ".join(f"{k} {v} ms" for k, v in m["timings"].items()) +
                     f" · Otsu threshold {m['otsu_threshold']:.0f}")
        disclaimer()

with tab_res:
    if out is None:
        st.info("Results appear here after an analysis.")
    elif "error" in out:
        error_card(*out["error"])
    else:
        res = out["result"]
        p, meta = res["prediction"], res["meta"]
        is_mel = p["label"] == "Melanoma"
        st.markdown(f"""<div class="card {'mel' if is_mel else 'ben'}">
            <div class="k">Prediction</div><h2>{p['label']}</h2>
            <div>Melanoma score: {p['score'] * 100:.0f}% (flagged at ≥ {p['threshold'] * 100:.0f}%)</div>
            </div>""", unsafe_allow_html=True)
        st.progress(min(max(p["score"], 0.0), 1.0), text="Model melanoma score")
        st.caption("The score is a model estimate, not a clinically calibrated probability. "
                   "The cutoff is set to the dataset's melanoma prevalence to favour sensitivity.")
        if meta["prediction_config_differs"]:
            mc = meta["model_config"]
            st.info(f"Prediction uses the default model ({mc['wavelet']}, level {mc['level']}, "
                    f"hair removal {'on' if mc['hair_removal'] else 'off'}). Your settings affect "
                    "the displayed pipeline steps only.")
        f = res["features"]
        abcd = {k: v for k, v in f.items() if not k.startswith(("L", "LL_"))}
        left, right = st.columns(2)
        with left:
            st.subheader("ABCD features")
            st.dataframe(pd.DataFrame({"feature": abcd.keys(), "value": np.round(list(abcd.values()), 3)}),
                         hide_index=True, width="stretch")
        with right:
            st.subheader("Subband energy")
            energy = {k.replace("_energy", ""): v for k, v in f.items() if k.endswith("_energy")}
            st.bar_chart(pd.Series(energy), color=NAVY)
        if out["sample"]:
            st.subheader("Expert mask comparison (sample image)")
            mask = cv2.imread(str(config.SAMPLES_DIR / f"{out['sample']}_mask.png"), 0) > 127
            d = pipeline.dice_vs_expert(res, mask)
            c = st.columns(3)
            show(c[0], disp(preprocessing.prepare_mask(mask), True), "Expert mask")
            show(c[1], disp(res["images"]["final_mask"], True), "Our mask")
            c[2].metric("Dice vs expert", f"{d:.3f}")
            st.caption("Sample images come from the training set, so this is not held-out performance.")
        disclaimer()

with tab_about:
    st.markdown(f"""
**Method.** Dermoscopy images are padded to a square and resized to 256×256. Hair is detected
with a morphological black-hat transform and removed by inpainting. A 2-D discrete wavelet
transform (Haar, Daubechies db4 or Symlet sym4, 1–3 levels) splits the image into an
approximation (LL) and detail subbands. The lesion is segmented by Otsu thresholding of the
coarse LL band followed by morphological clean-up. Wavelet energy/entropy features and ABCD
features (asymmetry, border, colour, diameter) feed an RBF support vector machine.

**Data.** PH2 dermoscopy database (200 images: 80 common nevi, 80 atypical nevi, 40
melanomas) with expert lesion masks. Results are 5-fold cross-validated, repeated over 3 seeds.

**Honest limits.** Only 40 melanomas, so sensitivity estimates are noisy. Segmentation is weaker
on large, textured melanomas. Wavelet features alone are weaker than ABCD features.

{DISCLAIMER}

**References.** Garnavi et al., IEEE TITB 2012 · Mallat, IEEE TPAMI 1989 · Otsu, IEEE TSMC 1979 ·
Barata et al., IEEE JBHI 2019 · Talavera-Martínez et al., IEEE Access 2021 · Yu et al., IEEE TMI 2017.
""")
